import json
import os
import re
import urllib.error
import urllib.request
from pathlib import Path
from typing import Optional

from dotenv import load_dotenv

# Load environment variables
env_path = Path(__file__).resolve().parent.parent / ".env"
load_dotenv(dotenv_path=env_path)

PROMPT_TEMPLATE_PATH = Path(__file__).resolve().parent / "prompts" / "html_code_validation_prompt.txt"


def _clean_html_response(raw_response: str) -> str:
    """
    Cleans raw LLM response:
    - Strips deepseek/reasoning tags (<think>...</think>)
    - Removes markdown code fences (```html ... ``` or ``` ... ```)
    - Extracts valid HTML from <!DOCTYPE html> / <html to </html> if surrounded by extra text
    """
    if not raw_response:
        return ""

    text = raw_response.strip()

    # 1. Strip reasoning tags
    text = re.sub(r"<think>[\s\S]*?</think>", "", text, flags=re.IGNORECASE).strip()

    # 2. Extract content from markdown code block if present
    block_match = re.search(r"```(?:html|xml)?\s*([\s\S]*?)\s*```", text, re.IGNORECASE)
    if block_match:
        text = block_match.group(1).strip()

    # 3. Extract from <!DOCTYPE or <html to </html>
    doc_start = text.lower().find("<!doctype html")
    if doc_start == -1:
        doc_start = text.lower().find("<html")

    doc_end = text.lower().rfind("</html>")
    if doc_start != -1 and doc_end != -1 and doc_end > doc_start:
        text = text[doc_start:doc_end + len("</html>")].strip()

    return text


def ValidateHTMLCodeAgent(html_code: str) -> str:
    """
    Node 7: HTML Code Validation Agent
    Passes ONLY the HTML code to the validation agent to:
    - Rewrite code if broken UI or overlapping elements exist
    - Rewrite code if not proper alignment of the PPT slide frame (16:9 aspect ratio)
    - Rewrite code if any syntax errors, unclosed tags, or broken CSS/JS exist (e.g. calc() inside JS)
    - Returns the proper, working HTML code.

    :param html_code: The presentation slide HTML code generated by PPTGenerationAgent.
    :return: Validated, cleaned, and properly formatted HTML code.
    """
    cleaned_input = (html_code or "").strip()
    if not cleaned_input:
        print("[!] [ValidateHTMLCodeAgent] Received empty HTML code; skipping validation.")
        return html_code

    if not PROMPT_TEMPLATE_PATH.exists():
        print(f"[!] [ValidateHTMLCodeAgent] Prompt template not found at {PROMPT_TEMPLATE_PATH}; returning original code.")
        return html_code

    try:
        with open(PROMPT_TEMPLATE_PATH, "r", encoding="utf-8") as f:
            prompt_template = f.read()
    except Exception as read_err:
        print(f"[!] [ValidateHTMLCodeAgent] Error reading prompt template: {read_err}; returning original code.")
        return html_code

    populated_prompt = prompt_template.replace("{{html_code}}", cleaned_input)

    # LLM configuration (uses standard LLM environment variables)
    base_url = os.getenv("LLM_BASE_URL", "https://api.groq.com/openai/v1").rstrip("/")
    api_key = os.getenv("LLM_API_KEY", "")
    model = os.getenv("LLM_MODEL", "openai/gpt-oss-120b")

    if not api_key:
        print("[!] [ValidateHTMLCodeAgent] LLM API key not configured; returning original HTML code.")
        return html_code

    endpoint_url = f"{base_url}/chat/completions" if not base_url.endswith("/chat/completions") else base_url

    request_data = {
        "model": model,
        "messages": [
            {
                "role": "user",
                "content": populated_prompt
            }
        ],
        "temperature": 0.1,
        "max_tokens": 8192
    }

    req = urllib.request.Request(
        endpoint_url,
        data=json.dumps(request_data).encode("utf-8"),
        headers={
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"
        },
        method="POST"
    )

    try:
        with urllib.request.urlopen(req, timeout=120) as resp:
            resp_bytes = resp.read()
            resp_json = json.loads(resp_bytes.decode("utf-8"))
            raw_content = resp_json["choices"][0]["message"]["content"]
            usage = resp_json.get("usage", {})

            # Log interaction to workflow logger
            try:
                from logs.llm_logger import log_agent_call
                log_agent_call(
                    node_name="Node 7: HTML Code Validation",
                    agent_name="HTML Code Validation Agent",
                    llm_input=populated_prompt,
                    llm_output=raw_content,
                    usage=usage
                )
            except Exception as log_err:
                print(f"[!] Warning logging HTML validation interaction: {log_err}")

            validated_html = _clean_html_response(raw_content)

            # Sanity check: Ensure valid HTML was returned, otherwise fallback to input
            if validated_html and ("<html" in validated_html.lower() or "<!doctype" in validated_html.lower()):
                return validated_html
            else:
                print("[!] [ValidateHTMLCodeAgent] Validated output lacked standard HTML root structure; using input code.")
                return html_code

    except Exception as err:
        print(f"[!] Warning in ValidateHTMLCodeAgent: {err}. Safely falling back to input HTML code.")
        return html_code
